openapi: "3.1.0"
info:
  title: "tiltakspenger_datadeling API"
  description: "tiltakspenger_datadeling API"
  version: "1.0.0"
servers:
  - url: "https://tiltakspenger-datadeling.intern.dev.nav.no"
paths:
  /behandlinger/perioder:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VedtakReqDTO"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MappingError"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/BehandlingResponse"
  /vedtak/detaljer:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VedtakReqDTO"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MappingError"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/VedtakDetaljerResponse"
  /vedtak/perioder:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VedtakReqDTO"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MappingError"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/VedtakDTO"
  /vedtak/tidslinje:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VedtakReqDTO"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MappingError"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VedtakTidslinjeResponse"
  /meldekort/detaljer:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VedtakReqDTO"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MappingError"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeldekortResponse"
components:
  schemas:
    VedtakReqDTO:
      type: "object"
      properties:
        ident:
          type: "string"
        fom:
          type: "string"
        tom:
          type: "string"
      required:
        - "ident"
    MappingError:
      type: "object"
      properties:
        feilmelding:
          type: "string"
      required:
        - "feilmelding"
    BehandlingResponse:
      type: "object"
      properties:
        behandlingId:
          type: "string"
        fom:
          type: "string"
          format: "date"
        tom:
          type: "string"
          format: "date"
      required:
        - "behandlingId"
        - "fom"
        - "tom"
    VedtakDetaljerResponse:
      type: "object"
      properties:
        fom:
          type: "string"
          format: "date"
        tom:
          type: "string"
          format: "date"
        rettighet:
          type: "string"
          enum:
            - "TILTAKSPENGER"
            - "TILTAKSPENGER_OG_BARNETILLEGG"
            - "INGENTING"
        vedtakId:
          type: "string"
        sakId:
          type: "string"
        saksnummer:
          type: "string"
        kilde:
          type: "string"
        sats:
          type: "integer"
          format: "int32"
        satsBarnetillegg:
          type: "integer"
          format: "int32"
      required:
        - "fom"
        - "tom"
        - "rettighet"
        - "vedtakId"
        - "sakId"
        - "kilde"
    Periode:
      type: "object"
      properties:
        fraOgMed:
          type: "string"
          format: "date"
        tilOgMed:
          type: "string"
          format: "date"
      required:
        - "fraOgMed"
        - "tilOgMed"
    BarnetilleggPeriode:
      type: "object"
      properties:
        antallBarn:
          type: "integer"
          format: "int32"
        periode:
          $ref: "#/components/schemas/Periode"
      required:
        - "antallBarn"
        - "periode"
    Barnetillegg:
      type: "object"
      properties:
        perioder:
          type: "array"
          items:
            $ref: "#/components/schemas/BarnetilleggPeriode"
      required:
        - "perioder"
    VedtakDTO:
      type: "object"
      properties:
        vedtakId:
          type: "string"
        rettighet:
          type: "string"
          enum:
            - "TILTAKSPENGER"
            - "TILTAKSPENGER_OG_BARNETILLEGG"
            - "INGENTING"
        periode:
          $ref: "#/components/schemas/Periode"
        kilde:
          type: "string"
          enum:
            - "TPSAK"
            - "ARENA"
        barnetillegg:
          $ref: "#/components/schemas/Barnetillegg"
        sats:
          type: "integer"
          format: "int32"
        satsBarnetillegg:
          type: "integer"
          format: "int32"
      required:
        - "vedtakId"
        - "rettighet"
        - "periode"
        - "kilde"
    VedtakTidslinjeResponse:
      type: "object"
      properties:
        tidslinje:
          type: "array"
          items:
            $ref: "#/components/schemas/VedtakResponse"
        alleVedtak:
          type: "array"
          items:
            $ref: "#/components/schemas/VedtakResponse"
      required:
        - "tidslinje"
        - "alleVedtak"
    VedtakResponse:
      type: "object"
      properties:
        vedtakId:
          type: "string"
        sakId:
          type: "string"
        saksnummer:
          type: "string"
        rettighet:
          type: "string"
          enum:
            - "TILTAKSPENGER"
            - "TILTAKSPENGER_OG_BARNETILLEGG"
            - "STANS"
            - "AVSLAG"
        periode:
          $ref: "#/components/schemas/Periode"
        barnetillegg:
          $ref: "#/components/schemas/Barnetillegg"
        vedtaksdato:
          type: "string"
          format: "date"
        valgteHjemlerHarIkkeRettighet:
          type: "string"
          enum:
            - "DELTAR_IKKE_PA_ARBEIDSMARKEDSTILTAK"
            - "ALDER"
            - "LIVSOPPHOLDSYTELSER"
            - "KVALIFISERINGSPROGRAMMET"
            - "INTRODUKSJONSPROGRAMMET"
            - "LONN_FRA_TILTAKSARRANGOR"
            - "LONN_FRA_ANDRE"
            - "INSTITUSJONSOPPHOLD"
            - "FREMMET_FOR_SENT"
        sats:
          type: "integer"
          format: "int32"
        satsBarnetillegg:
          type: "integer"
          format: "int32"
      required:
        - "vedtakId"
        - "sakId"
        - "saksnummer"
        - "rettighet"
        - "periode"
        - "vedtaksdato"
    MeldekortResponse:
      type: "object"
      properties:
        meldekortKlareTilUtfylling:
          type: "array"
          items:
            $ref: "#/components/schemas/MeldekortKlartTilUtfylling"
        godkjenteMeldekort:
          type: "array"
          items:
            $ref: "#/components/schemas/GodkjentMeldekort"
      required:
        - "meldekortKlareTilUtfylling"
        - "godkjenteMeldekort"
    MeldekortKlartTilUtfylling:
      type: "object"
      properties:
        id:
          type: "string"
        kjedeId:
          type: "string"
        sakId:
          type: "string"
        saksnummer:
          type: "string"
        opprettet:
          type: "string"
          format: "datetime"
        fraOgMed:
          type: "string"
          format: "date"
        tilOgMed:
          type: "string"
          format: "date"
        maksAntallDagerForPeriode:
          type: "integer"
          format: "int32"
        girRett:
          description:
            "Dette er en Map<LocalDate, Boolean>, som dessverre ikke lar seg modellere med swagger"
          type: "object"
          additionalProperties:
            type: "object"
        kanFyllesUtFraOgMed:
          type: "string"
          format: "date"
      required:
        - "id"
        - "kjedeId"
        - "sakId"
        - "saksnummer"
        - "opprettet"
        - "fraOgMed"
        - "tilOgMed"
        - "maksAntallDagerForPeriode"
        - "girRett"
        - "kanFyllesUtFraOgMed"
    GodkjentMeldekort:
      type: "object"
      properties:
        kjedeId:
          type: "string"
        sakId:
          type: "string"
        meldeperiodeId:
          type: "string"
        saksnummer:
          type: "string"
        mottattTidspunkt:
          type: "string"
          format: "datetime"
        vedtattTidspunkt:
          type: "string"
          format: "datetime"
        behandletAutomatisk:
          type: "boolean"
        korrigert:
          type: "boolean"
        fraOgMed:
          type: "string"
          format: "date"
        tilOgMed:
          type: "string"
          format: "date"
        meldekortdager:
          type: "array"
          items:
            $ref: "#/components/schemas/MeldekortDag"
        opprettet:
          type: "string"
          format: "datetime"
        sistEndret:
          type: "string"
          format: "datetime"
      required:
        - "kjedeId"
        - "sakId"
        - "meldeperiodeId"
        - "saksnummer"
        - "vedtattTidspunkt"
        - "behandletAutomatisk"
        - "korrigert"
        - "fraOgMed"
        - "tilOgMed"
        - "meldekortdager"
        - "opprettet"
        - "sistEndret"
    MeldekortDag:
      type: "object"
      properties:
        dato:
          type: "string"
          format: "date"
        status:
          type: "string"
          enum:
            - "DELTATT_UTEN_LONN_I_TILTAKET"
            - "DELTATT_MED_LONN_I_TILTAKET"
            - "FRAVAER_SYK"
            - "FRAVAER_SYKT_BARN"
            - "FRAVAER_GODKJENT_AV_NAV"
            - "FRAVAER_ANNET"
            - "IKKE_BESVART"
            - "IKKE_TILTAKSDAG"
            - "IKKE_RETT_TIL_TILTAKSPENGER"
        reduksjon:
          type: "string"
          enum:
            - "INGEN_REDUKSJON"
            - "UKJENT"
            - "YTELSEN_FALLER_BORT"
      required:
        - "dato"
        - "status"
        - "reduksjon"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]