cluster-fss: dev-fss
ingress:
  url: https://tiltakspenger-datadeling.intern.dev.nav.no
outboundExternalUrls:
  tiltakspengerarena: tiltakspenger-arena.dev-fss-pub.nais.io
tenant: trygdeetaten.no
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: false
  tier: db-f1-micro
kafka-pool: "nav-dev"