cluster-fss: prod-fss
ingress:
  url: https://tiltakspenger-datadeling.intern.nav.no
outboundExternalUrls:
  tiltakspengerarena: tiltakspenger-arena.prod-fss-pub.nais.io
tenant: nav.no
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: true
  tier: db-custom-1-3840