apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-datadeling
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{ tenant }}
      allowAllUsers: true
  replicas:
    min: 1
    max: 1
  ingresses:
    - {{ ingress.url }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-vedtak
          namespace: tpts
          cluster: {{ cluster }}
        - application: saas-proxy
          namespace: teamcrm
          cluster: {{ cluster }}
        - application: arena
          namespace: teamarenanais
          cluster: {{ cluster-fss }}
        - application: modiapersonoversikt-api
          namespace: personoversikt
    outbound:
      rules:
        - application: tiltakspenger-vedtak
      external:
        - host: {{outboundExternalUrls.tiltakspengerarena}}
