apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-datadeling
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      allowAllUsers: true
  replicas:
    min: 2
    max: 2
  ingresses:
    - {{ingress.url}}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{ kafka-pool }}
  leaderElection: true
  gcp:
    sqlInstances:
      - name: tiltakspenger-datadeling
        type: POSTGRES_16
        tier: {{sqlInstances.tier}}
        diskAutoresize: {{sqlInstances.diskAutoresize}}
        pointInTimeRecovery: {{sqlInstances.pointInTimeRecovery}}
        databases:
          - name: datadeling
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-saksbehandling-api
          namespace: tpts
          cluster: {{cluster}}
          permissions:
            roles:
              - "lagre-tiltakspenger-hendelser"
        - application: saas-proxy
          namespace: teamcrm
          cluster: {{cluster}}
          permissions:
            roles:
              - "les-vedtak"
        - application: arena
          namespace: teamarenanais
          cluster: {{cluster-fss}}
          permissions:
            roles:
              - "les-vedtak"
              - "les-behandling"
        - application: modiapersonoversikt-api
          namespace: personoversikt
          permissions:
            roles:
              - "les-vedtak"
        # https://behandlingskatalog.intern.nav.no/process/purpose/TILLEGGSSTOENADER/c22075da-7ae4-4ce6-bf84-20a4ac0a73c9
        - application: tilleggsstonader-integrasjoner
          namespace: tilleggsstonader
          permissions:
            roles:
              - "les-vedtak"
              - "les-behandling"
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: {{outboundExternalUrls.tiltakspengerarena}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
